### ISSUE TITLE
Size is reported wrong under windows. (With fix!)

### ISSUE THREAD

**Issue by sgtwilko** [seriouslysean/spacewatch#4]
When runngin this plugin under IIS on windows the allocated/free space is reported incorrectly.

I have no idea what it was reporting (it wasn't the disk space on my server, nor was it the quota set for the WP folder).
I Fixed the issue by changing:
    const SYSTEM_ROOT = '/';
to
   const SYSTEM_ROOT = '.';

This allowed it to pick up the correct quota information and is now displaying correctly on the dashboard.

**Comment by seriouslysean** [comment]
@sgtwilko I know this is from a while ago, but I just noticed your comment and fix. I'll see if I can get it in to an update (with credit) and update it for the latest version of WordPress. Thanks so much for posting that!
